server:
  port: 8050
  servlet:
    context-path: /api
spring:
  main:
    allow-bean-definition-overriding: true
  mail:
    host:
    username:
    password:
    default-encoding: UTF-8
  redis:
    #    host: 47.102.207.156
    host: r-uf6z45ljpjufw6myqspd.redis.rds.aliyuncs.com
    #    database: 2
    database: 0
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 600 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 300 #连接池中的最大空闲连接
        min-idle: 10 #连接池中的最小空闲连接
    password: Lynkbey888
  datasource:
    url: jdbc:mysql://rm-uf642uoe0h9dx6p25xo.mysql.rds.aliyuncs.com/offer_ehrsip?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    #    url: jdbc:mysql://47.102.207.156:3306/parkinfo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: ehrsip
    password: Password@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    username: root
  #    password: Lynkbey888
  #    driver-class-name: net.sf.log4jdbc.DriverSpy
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect  #不加这句则默认为myisam引擎
  rabbitmq:
    host: 47.102.207.156
    port: 5672
    username: admin
    password: Lynkbey888
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  level:
    jdbc:
      sqlonly: info
      audit: off
      resultset: off
      connection: off
      sqltiming: off
    com:
      hhsj:
        mybatis: DEBUG
  file: /developer/logs/lingouu-web/parkinfo-web.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'